---
title: "GRP 2018 Cut Off"
author: "Aashish"
date: "7 September 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## ResultSet


```{r ,echo=FALSE, results="asis"}
suppressWarnings(library(xlsx, quietly = TRUE, warn.conflicts = FALSE ))
suppressWarnings(library(dplyr, quietly = TRUE, warn.conflicts = FALSE))
suppressWarnings(library(knitr, quietly = TRUE, warn.conflicts = FALSE))

g_data_root <- "."
g_geresults_folder <- "rawresults"
g_max_marks_apti <- 40

create_master_data_set <- function(x) 
{
      res <- read.xlsx(x,1)
      
      v1 <- res %>% select(Name, Email, Institute, CGPA.Percentage, Phone.Number, Degree, Report.Access.URL, Programming..350.0. , Technical.Dev.Medium, Technical.Dev.Easy, Technical.Dev.C...Easy , Aptitude.Medium, Aptitude.Easy)
      
      names(v1) <- c("name", "email" ,  "institute" , "cgpa" , "phone" , "degree" , "url" , "programming"  , "techmed" , "techeasy" , "techcpp" , "aptmed" , "apteasy")
  

      v2 <- v1 %>% mutate (filename = basename(x)) 
      

      return(v2)  
  
}


allocation_strategy_b <- function(input_data_set) 
  {

    g_programming_pct_to_use <- 22.8571
    
      v2 <- input_data_set %>% mutate ( programming = as.numeric(levels(programming))[programming] , 
                            aptmed = as.numeric(levels(aptmed))[aptmed],
                            apteasy = as.numeric(levels(apteasy))[apteasy],
                            techmed = as.numeric(levels(techmed))[techmed],
                            techeasy = as.numeric(levels(techeasy))[techeasy],
                            techcpp = as.numeric(levels(techcpp))[techcpp] ,
                            TechMcq = techmed + techeasy + techcpp,
                            Aptitude = apteasy + aptmed, 
                            AptitudePct = Aptitude * 100 / g_max_marks_apti ,
                            TechPct = (programming * g_programming_pct_to_use) / 100 +  techmed + techeasy + techcpp,
                            CSTechAptitudePct = round((techmed +techeasy ) * 100 / 15),  
                            categoryDev1 = ifelse(programming >=200 , 1 , 0),
                            categoryDev2 = ifelse((AptitudePct >=75 & TechPct >= 35) , 1 , 0),
                            categoryDev3 = ifelse((AptitudePct >=50 & TechPct >= 50) , 1 , 0),
                            categoryDev4 = 'NA',
                            allocationCS = ifelse ( AptitudePct >= 85 & CSTechAptitudePct >= 80 , 1 , 0),
                            allocationDev = ifelse ( (categoryDev1 + categoryDev2 + categoryDev3 ) > 0  , 1 , 0),
                            allocation = ifelse ( allocationDev > 0  , "Dev" , 
                                                  ifelse ( allocationCS > 0 , "CS" , "No")
                                                  ),
                            strategy = "Strategy B"
                            ) 
                            

      v3 <- v2 %>% mutate( allocation = ifelse( allocation == "CS" , 
			ifelse( grepl('_igdtuw_|_mait_', filename), "CS", "No"),
			allocation))  %>% select (name, email ,  institute , cgpa , phone , degree , url , programming  , techmed , techeasy , techcpp , aptmed , apteasy , TechMcq, Aptitude , CSTechAptitudePct, allocation , filename ,categoryDev1 , categoryDev2, categoryDev3, categoryDev4, allocationDev,  allocationCS , strategy, TechPct) 

      
      return(v3)
  }



allocation_strategy_c <- function(input_data_set) 
  {

      v2 <- input_data_set %>% mutate ( programming = as.numeric(levels(programming))[programming] , 
                            aptmed = as.numeric(levels(aptmed))[aptmed],
                            apteasy = as.numeric(levels(apteasy))[apteasy],
                            techmed = as.numeric(levels(techmed))[techmed],
                            techeasy = as.numeric(levels(techeasy))[techeasy],
                            techcpp = as.numeric(levels(techcpp))[techcpp] ,
                            TechMcq = techmed + techeasy + techcpp,
                            Aptitude = apteasy + aptmed, 
                            AptitudePct = Aptitude * 100 / g_max_marks_apti ,
                            CSTechAptitudePct = round((techmed +techeasy ) * 100 / 15),  
                            categoryDev1 = ifelse(programming >=200 , 1 , 0),
                            categoryDev2 = ifelse((programming >=120 & Aptitude >= 20 & TechMcq >= 8) , 1 , 0),
                            categoryDev3 = ifelse((programming >=100 & Aptitude >= 35 & TechMcq >= 10) , 1 , 0),
                            categoryDev4 = ifelse((programming >=100 & Aptitude >= 30 & TechMcq >= 15) , 1 , 0),
                            allocationCS = ifelse ( AptitudePct >= 85 & CSTechAptitudePct >= 80 , 1 , 0),
                            allocationDev = ifelse ( (categoryDev1 + categoryDev2 + categoryDev3 + categoryDev4) > 0  , 1 , 0),
                            allocation = ifelse ( allocationDev > 0  , "Dev" , 
                                                  ifelse ( allocationCS > 0 , "CS" , "No")
                                                  ),
                            strategy = "Strategy C"
                            ) 
                            

      v3 <- v2 %>% mutate( allocation = ifelse( allocation == "CS" , 
			ifelse( grepl('_igdtuw_|_mait_', filename), "CS", "No"),
			allocation))  %>% select (name, email ,  institute , cgpa , phone , degree , url , programming  , techmed , techeasy , techcpp , aptmed , apteasy , TechMcq, Aptitude , CSTechAptitudePct, allocation , filename ,categoryDev1 , categoryDev2, categoryDev3, categoryDev4, allocationDev,  allocationCS , strategy) 

      
      return(v3)
  }


heresultspath = paste( g_data_root , g_geresults_folder , sep = "/")
files <- list.files(path=heresultspath, pattern="*.xls", full.names=T, recursive=FALSE)
  

master_data_set <- do.call(rbind,lapply(files, create_master_data_set ))
#output_file <- format(Sys.time(), "master-list-%Y%m%d-%H%M%S.csv")
#write.table(master_data_set, output_file, sep="," , row.names = F)


cutoff_list <- allocation_strategy_c(master_data_set)
output_file <- format(Sys.time(), "cutoff_list_strategy-C--%Y%m%d-%H%M%S.csv")
write.table(cutoff_list, output_file, sep="," , row.names = F)

to_display <- cutoff_list %>% filter (allocation != 'No') %>% select (name, email ,  institute , cgpa , phone , degree,programming, TechMcq, Aptitude , allocation)

if ( nrow(to_display) > 0 ) {
  print(paste("## Exported Results as CSV: ", output_file))
  
  kable(to_display)
  
} else {
g_data_root <- "."
g_geresults_folder <- "rawresults"

    print(paste("You need to place raw results file in folder: ", g_data_root , "/" , "g_geresults_folder"))
  
}


```

